var express = require('express');
var router  = express.Router();
var passport = require('passport');
var shortid = require('shortid');

var Post = require('../models/post');
var Coordinate = require('../models/coordinate');
var User = require('../models/user');
var Img = require('../models/img');
var Tag = require('../models/tag');

router.post('/create', function createPost(req, res, next) {
  // TODO: redirect if unauthorized access detected
  var user = {}; // TODO: pass here current user object;
  var postToCreate = {}; // TODO: pass here sent data object;

  var coordinate = new Coordinate();
  coordinate.id = shortid.generate();
  coordinate.latitude = postToCreate.latitude;
  coordinate.longtitude = postToCreate.longtitude;
  coordinate.save();

  var tags; // TODO: it should be one tag per item ?

  var img = new Img();
  img.id = shortid.generate();
  img.src = postToCreate.linkToImage;
  img.save();

  var post = new Post();
  post.id = shortid.generate();
  post.title = postToCreate.title;
  post.description = postToCreate.description;
  post.type = postToCreate.type;
  post.date = postToCreate.date; // TODO: or it should be generated by server ?

  post.coordinate_id = coordinate.id;
  post.user_id = user.id;
  post.img_id = img.id;

  // post.tag_id = tag.id;
  post.save();

  res.status(200).send();
});

router.get('/:postId', function getPostById(req, res, next) {
  // TODO: redirect if unauthorized access detected

  Post
    .where({ id: req.params.id })
    .findOne()
    .then(function (post) {

      // TODO: refactor callback hell with promises
      Coordinate
        .where({ id: post.coordinate_id })
        .findOne()
        .then(function (coordinate) {
          post.coordinate = coordinate;

          User
            .where({ id: post.user_id })
            .findOne()
            .then(function (user) {
              post.user = user;

              Img
                .where({ id: post.img_id })
                .findOne()
                .then(function (img) {
                  post.img = img;

                  Tag
                    .where({ id: post.tag_id })
                    .findOne()
                    .then(function (tag) {
                      post.tag = tag;

                      res.render('post', {
                        post: post,
                      });
                    });
                });
            });
        });
    });
});
